; ─────────────────────────────────────────────────────────
;  AuraLUX - Firmware ESP32 (Redis Version)
;  PlatformIO Configuration
; ─────────────────────────────────────────────────────────

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    bblanchon/ArduinoJson@^6.21.3
    adafruit/Adafruit NeoPixel@^1.12.0

monitor_speed = 115200
upload_speed = 460800
upload_resetmethod = ck
upload_port_timeout = 30
upload_timeout = 30
